openapi: 3.0.0
info:
  title: prediction-api
  version: 1.0.0
servers:
- url: /
paths:
  /api/1_year_prediction:
    post:
      tags:
      - Prediction
      summary: Get 1-Year Prediction
      description: |
        This endpoint predicts a value based on the provided dictionary of type Dict[str, Union[str, int]].
      operationId: api1_year_prediction_post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                anyOf:
                - type: string
                - type: number
        required: true
      responses:
        "200":
          description: Successful prediction
          content:
            application/json:
              schema:
                type: object
                properties:
                  fraction:
                    type: number
                  probability:
                    type: number
                x-content-type: application/json
        "400":
          description: Bad request
      x-openapi-router-controller: swagger_server.controllers.prediction_controller
components:
  schemas:
    SurveyResults:
      type: object
      additionalProperties:
        anyOf:
        - type: string
        - type: integer

