
version: "3.9"
services:
  flask:
    restart: always
    container_name: flask_api
    command: -m swagger_server
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - db-net

  frontend:
    restart: always
    command: npm run start_docker
    container_name: frontend
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    stdin_open: true
    depends_on:
      - flask
    networks:
      - db-net


networks:
  db-net:
    driver: bridge